# Generated by Django 2.1.5 on 2019-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0008_auto_20190124_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
