# Generated by Django 2.1.5 on 2019-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0011_auto_20190201_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='appkraft'),
        ),
    ]
