# Generated by Django 2.1.5 on 2019-02-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190202_1141'),
        ('appkraft', '0012_auto_20190201_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='ganho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
