# Generated by Django 2.1.5 on 2019-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0013_auto_20190226_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='observacoes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
