# Generated by Django 2.1.5 on 2019-08-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0014_auto_20190227_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='codigo_produto',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='marca',
        ),
    ]
