# Generated by Django 2.1.5 on 2019-02-01 18:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ESCOLA', 'Escola'), ('FORNECEDOR', 'Fornecedor'), ('FUNCIONARIO', 'Funcionario')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=2, verbose_name=accounts.models.Perfil)),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('aniversario', models.DateField()),
                ('telefone', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=11)),
                ('uf', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=50)),
                ('n_ie', models.CharField(max_length=50)),
                ('n_im', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
