# Generated by Django 2.1.5 on 2019-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil',
            field=models.CharField(choices=[('1', 'Cliente'), ('2', 'Escola'), ('3', 'Fornecedor'), ('4', 'Funcionario')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='perfil',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='perfil',
            field=models.ManyToManyField(to='accounts.Perfil'),
        ),
    ]
