# Generated by Django 2.1.5 on 2019-04-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_pessoa_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='aniversario',
            new_name='aniverssario',
        ),
    ]
