# Generated by Django 2.1.5 on 2019-02-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appkraft', '0014_auto_20190227_0927'),
        ('accounts', '0003_auto_20190202_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Pessoa')),
                ('produtos', models.ManyToManyField(blank=True, to='appkraft.Produtos')),
            ],
        ),
    ]
