# Generated by Django 2.1.5 on 2019-02-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0014_auto_20190227_0927'),
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkraft.Produtos')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caixa.Venda')),
            ],
        ),
    ]
