# Generated by Django 2.1.5 on 2019-02-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_itemdopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
    ]
