# Generated by Django 2.1.5 on 2019-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_remove_venda_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
