# Generated by Django 2.1.5 on 2019-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdopedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
