# Generated by Django 2.1.5 on 2019-08-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_venda_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('observacao', models.TextField(max_length=190)),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caixa.Mesa'),
        ),
    ]
