# Generated by Django 2.1.5 on 2019-09-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caixa.Table'),
        ),
    ]
