# Generated by Django 2.1.5 on 2019-04-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appkraft', '0014_auto_20190227_0927'),
        ('accounts', '0008_auto_20190412_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.ManyToManyField(to='appkraft.Produtos')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Pessoa')),
            ],
        ),
    ]
