# Generated by Django 2.1.5 on 2019-04-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkraft', '0014_auto_20190227_0927'),
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='nome',
            new_name='lista',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='itens',
        ),
        migrations.AddField(
            model_name='itemlista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.Lista'),
        ),
        migrations.AddField(
            model_name='itemlista',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appkraft.Produtos'),
        ),
    ]
